export type SlideTemplate = 'title' | 'content' | 'code' | 'table' | 'split' | 'diagram';
export type TransitionType = 'fade' | 'slideLeft' | 'zoom';
export type BackgroundScene = 'particles' | 'geometric' | 'flowingLines' | 'neuralNetwork' | 'circuitBoard';

export interface SlideSection {
  type: 'text' | 'code' | 'table' | 'list' | 'quote' | 'diagram';
  content?: string;
  language?: string;
  headers?: string[];
  rows?: string[][];
  items?: string[];
}

export interface SlideData {
  id: number;
  title: string;
  subtitle?: string;
  template: SlideTemplate;
  transition: TransitionType;
  background: BackgroundScene;
  accentColor: string;
  sections: SlideSection[];
  footer?: string;
}

export const slides: SlideData[] = [
  // ─────────────────────────────────────────────────
  // SLIDE 1 — Welcome / Intro
  // ─────────────────────────────────────────────────
  {
    id: 1,
    title: 'Agentic Engineering',
    subtitle: 'Building AI-Native Apps in Under 2 Hours',
    template: 'title',
    transition: 'fade',
    background: 'particles',
    accentColor: '#0bbccc',
    sections: [
      { type: 'text', content: 'Bangalore Hackathon' },
      { type: 'text', content: 'Presented by rUv (Reuven Cohen)' },
      { type: 'text', content: 'Creator of Claude Flow & RuVector' },
    ],
    footer: 'The future of software engineering is agentic.',
  },

  // ═══════════════════════════════════════════════════
  // BONUS DIVIDER — This Presentation
  // ═══════════════════════════════════════════════════
  {
    id: 2,
    title: 'Bonus: This Deck is AI-Generated',
    subtitle: 'Built With the Same Tools You\'ll Learn Today',
    template: 'title',
    transition: 'zoom',
    background: 'neuralNetwork',
    accentColor: '#f9a825',
    sections: [
      { type: 'text', content: 'This entire presentation -- 3D backgrounds, animated transitions, interactive navigation -- was generated by AI agents.' },
      { type: 'text', content: 'It\'s yours. Clone the repo and use it as a template for your own decks.' },
    ],
    footer: 'Agentic engineering in action -- even the slides are AI-built.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 3 — Bonus: Deck Features & Download
  // ─────────────────────────────────────────────────
  {
    id: 3,
    title: 'Interactive Animated Presentation',
    subtitle: 'Clone It, Customize It, Present It',
    template: 'split',
    transition: 'slideLeft',
    background: 'neuralNetwork',
    accentColor: '#f9a825',
    sections: [
      { type: 'list', items: [
        'Three.js animated backgrounds -- Poincare disk particles, geodesic arcs, orbital rings',
        'Framer Motion slide transitions -- fade, slide, zoom',
        'Keyboard, mouse wheel, and touch/swipe navigation',
        'Side panel with slide thumbnails and quick jump',
        'Fullscreen mode and PDF export',
        'Cognitum design system -- glass morphism, gradient accents, glow effects',
        'Data-driven slides -- edit slides.ts, everything updates',
      ]},
      { type: 'code', language: 'bash', content: '# Run the presentation\ngit clone https://github.com/ruvnet/huron-bangalore\ncd huron-bangalore\n./start-presentation.sh\n# Opens at http://localhost:3003\n\n# Or run manually:\ncd docs/presentation\nnpm install && npm run dev' },
      { type: 'table', headers: ['Stack', 'Tech'], rows: [
        ['Framework', 'React 18 + TypeScript + Vite'],
        ['3D Graphics', 'Three.js (@react-three/fiber + drei)'],
        ['Animation', 'Framer Motion'],
        ['Styling', 'Tailwind CSS + Cognitum tokens'],
        ['Slides', 'Data-driven from slides.ts'],
      ]},
    ],
    footer: 'github.com/ruvnet/huron-bangalore -- fork it, make it yours.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 4 — About rUv
  // ─────────────────────────────────────────────────
  {
    id: 4,
    title: 'rUv (Reuven Cohen)',
    subtitle: 'Agentic Engineer & Independent AI Consultant',
    template: 'split',
    transition: 'fade',
    background: 'neuralNetwork',
    accentColor: '#0bbccc',
    sections: [
      { type: 'code', language: 'json', content: '{\n  "name": "rUv",\n  "role": "Agentic Engineer",\n  "approach": "Technical, outcome-driven\n    mentoring with practical\n    implementations",\n  "expertise": [\n    "AI Agent Development",\n    "PACT Methodologies",\n    "Autonomous Systems",\n    "Multi-Agent Coordination",\n    "LLM Infrastructure"\n  ]\n}' },
      { type: 'text', content: 'Independent AI consultant working with some of the largest companies in the world on enterprise AI architecture and management strategies. Pivotal role in the 2023 deployment of EY.ai -- 400,000+ employees, 1.5M end users, $1.4B budget.' },
      { type: 'list', items: [
        'Coined "Infrastructure as a Service" (2005) -- one year before AWS EC2',
        'Inaugural member of the Amazon Web Services advisory board',
        'Co-authored the first US Cloud Definition with NIST (2009)',
        'Founded Enomaly Inc. & co-founded CloudCamp (100,000+ participants)',
        'Alpha/beta tester for OpenAI, Napster, AOL, Sierra Online',
        '30+ year career spanning cloud, AI, and enterprise technology',
      ]},
    ],
    footer: 'ruv.net',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 5 — PACT & Trusted Partners
  // ─────────────────────────────────────────────────
  {
    id: 5,
    title: 'Agentics & Trusted Partners',
    subtitle: 'PACT: Proactive, Autonomous, Collaborative, and Targeted',
    template: 'content',
    transition: 'fade',
    background: 'flowingLines',
    accentColor: '#0bbccc',
    sections: [
      { type: 'quote', content: 'Agentics /\u0259\u02C8d\u0292ent\u026Aks/ -- The field of AI engineering focused on creating intelligent systems that are Proactive, Autonomous, Collaborative, and Targeted.' },
      { type: 'list', items: [
        'Develop agents for specific, valuable tasks with measurable outcomes',
        'Optimize for reliability and autonomy with minimal oversight',
        'Design for collaboration from the start -- true power emerges from coordinated multi-agent systems',
      ]},
      { type: 'table', headers: ['Organization', 'Engagement'], rows: [
        ['AWS', 'Advisory Board (inaugural member)'],
        ['EY', 'Enterprise AI architecture ($1.4B)'],
        ['Microsoft', 'AI consulting & engineering'],
        ['OpenAI', 'Alpha/beta testing & AI engineering'],
        ['NIST', 'Co-authored US Cloud Definition'],
        ['Meta', 'AI consulting'],
        ['Baxter / Kellogg / UofT', 'Strategic consulting'],
        ['Fortune 500+', 'Dozens of enterprises across tech, finance, healthcare'],
      ]},
    ],
    footer: 'Delivering enterprise-grade AI solutions to global industry leaders',
  },

  // ═══════════════════════════════════════════════════
  // SECTION DIVIDER — What We're Building
  // ═══════════════════════════════════════════════════
  {
    id: 6,
    title: 'What We\'re Building',
    subtitle: 'A Real-World Grants Management System -- From Zero to Production',
    template: 'title',
    transition: 'zoom',
    background: 'circuitBoard',
    accentColor: '#2eb85c',
    sections: [
      { type: 'text', content: 'An enterprise-grade system built entirely by AI agent swarms in under 2 hours.' },
      { type: 'text', content: 'Semantic search, multi-tenant security, 21-state workflow, offline WASM -- the full stack.' },
    ],
    footer: 'From architecture to deployment, powered by coordinated AI agents.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 7 — Grants Management System
  // ─────────────────────────────────────────────────
  {
    id: 7,
    title: 'The Grants Management System',
    subtitle: 'Huron Grants Consulting (HCG)',
    template: 'split',
    transition: 'slideLeft',
    background: 'circuitBoard',
    accentColor: '#2eb85c',
    sections: [
      { type: 'text', content: 'Universities manage 1000s of grant proposals across dozens of funding agencies with complex compliance, budgets, and deadlines.' },
      { type: 'list', items: [
        'Semantic search across thousands of proposals',
        'Multi-tenant data isolation (university-grade security)',
        '21-state proposal lifecycle workflow',
        'Self-learning search that improves with every query',
        'Offline-capable WASM vector search',
        'Modern dashboard with real-time status pipeline',
      ]},
      { type: 'table', headers: ['Context', 'Responsibility', 'Key Entity'], rows: [
        ['Proposal Management', 'Lifecycle from draft to submission', 'Proposal'],
        ['Budget Management', 'Line items, F&A rates, variance', 'Budget'],
        ['Award Management', 'Funded grants, modifications', 'Award'],
        ['SF424 Forms', 'Federal form generation', 'FormPackage'],
        ['Compliance', 'IRB/IACUC protocols', 'ComplianceItem'],
        ['Financial Accounts', 'Integration with finance systems', 'Account'],
        ['Identity (shared)', 'People and organizations', 'Person'],
      ]},
    ],
    footer: 'Built from scratch. In under 2 hours. Using AI agent swarms.',
  },

  // ═══════════════════════════════════════════════════
  // SECTION DIVIDER — The Agentic Approach
  // ═══════════════════════════════════════════════════
  {
    id: 8,
    title: 'The Agentic Approach',
    subtitle: 'How AI Agent Swarms Replace Traditional Development Workflows',
    template: 'title',
    transition: 'zoom',
    background: 'particles',
    accentColor: '#0bbccc',
    sections: [
      { type: 'text', content: 'Describe intent. Deploy swarms. Ship production code.' },
      { type: 'text', content: 'A new paradigm where humans steer and AI agents execute in parallel.' },
    ],
    footer: 'Intent-driven development with multi-agent coordination.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 9 — What is Agentic Engineering
  // ─────────────────────────────────────────────────
  {
    id: 9,
    title: 'What is Agentic Engineering?',
    subtitle: 'The Paradigm Shift',
    template: 'split',
    transition: 'slideLeft',
    background: 'particles',
    accentColor: '#0bbccc',
    sections: [
      { type: 'table', headers: ['Traditional Development', 'Agentic Engineering'], rows: [
        ['Developer writes all code', 'AI agents write code, human steers'],
        ['Sequential workflow', 'Parallel swarm execution'],
        ['Manual testing', 'Self-validating pipelines'],
        ['Static architecture', 'Self-learning, self-optimizing'],
        ['Hours to prototype', 'Minutes to prototype'],
      ]},
      { type: 'list', items: [
        'Intent over Implementation -- describe WHAT, agents figure out HOW',
        'Swarm Parallelism -- 6 agents working simultaneously',
        'Architectural Guardrails -- ADRs + DDD prevent agent drift',
        'Memory & Learning -- agents remember patterns, improve over time',
        'Human-in-the-Loop -- you steer, agents execute',
      ]},
    ],
    footer: 'Human \u2192 Intent \u2192 Agent Swarm \u2192 Working System',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 10 — The Toolchain
  // ─────────────────────────────────────────────────
  {
    id: 10,
    title: 'The Toolchain',
    subtitle: 'Claude Code + Claude Flow + RuVector',
    template: 'diagram',
    transition: 'slideLeft',
    background: 'circuitBoard',
    accentColor: '#2eb85c',
    sections: [
      { type: 'diagram', content: 'TOOLCHAIN_STACK' },
      { type: 'table', headers: ['Tool', 'What It Does', 'In Our Project'], rows: [
        ['Claude Code', 'AI-powered CLI that reads your codebase', 'Write Go handlers, React components, tests'],
        ['Claude Flow', 'Coordinates multiple AI agents in parallel', '6-agent swarms building features simultaneously'],
        ['RuVector', 'Semantic search, embeddings, self-learning', 'Proposal search, offline WASM, relevance ranking'],
      ]},
      { type: 'quote', content: 'The CLAUDE.md file is the single most important artifact for controlling AI agent behavior. Agents read it first, every time.' },
    ],
    footer: 'Three tools, one workflow.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 11 — Setup
  // ─────────────────────────────────────────────────
  {
    id: 11,
    title: 'Setup: One Command to Start',
    subtitle: './start-hacking.sh -- System Check, Install, Launch',
    template: 'code',
    transition: 'slideLeft',
    background: 'flowingLines',
    accentColor: '#f9a825',
    sections: [
      { type: 'code', language: 'bash', content: '# Clone the repo and run the quick-start script\ngit clone https://github.com/ruvnet/huron-bangalore.git\ncd huron-bangalore\n\n# One command does everything:\n./start-hacking.sh' },
      { type: 'code', language: 'bash', content: '# What start-hacking.sh does:\n# [1/4] System Check   -- node, npm, git, npx\n# [2/4] Claude Flow    -- npm install -g @claude-flow/cli@latest\n# [3/4] Claude Code    -- npm install -g @anthropic-ai/claude-code\n# [4/4] Launch         -- claude --dangerously-skip-permissions\n\n# You\'ll be inside Claude Code, ready to build.' },
      { type: 'table', headers: ['Step', 'What Happens', 'Time'], rows: [
        ['System Check', 'Validates node, npm, git, npx', '~2 sec'],
        ['Claude Flow CLI', 'Installs multi-agent orchestration', '~15 sec'],
        ['Claude Code', 'Installs AI-powered coding CLI', '~15 sec'],
        ['Launch', 'Opens Claude Code with full permissions', 'Instant'],
      ]},
    ],
    footer: 'One script. Four steps. You\'re hacking in under 60 seconds.',
  },

  // ═══════════════════════════════════════════════════
  // SECTION DIVIDER — Architecture & Guardrails
  // ═══════════════════════════════════════════════════
  {
    id: 12,
    title: 'Architecture & Guardrails',
    subtitle: 'How ADRs and Domain-Driven Design Keep AI Agents on Track',
    template: 'title',
    transition: 'zoom',
    background: 'geometric',
    accentColor: '#0bbccc',
    sections: [
      { type: 'text', content: 'Without guardrails, agents drift. With architecture decisions, they converge.' },
      { type: 'text', content: '10 ADRs, 7 bounded contexts, 4 layers of defense against agent chaos.' },
    ],
    footer: 'Architecture is the compass that guides autonomous agents.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 13 — ADRs & DDD
  // ─────────────────────────────────────────────────
  {
    id: 13,
    title: 'ADRs & DDD: Guardrails for Agents',
    subtitle: 'The 4-Layer Anti-Drift Architecture',
    template: 'table',
    transition: 'fade',
    background: 'geometric',
    accentColor: '#0bbccc',
    sections: [
      { type: 'diagram', content: 'DRIFT_COMPARISON' },
      { type: 'table', headers: ['ADR', 'Controls', 'Prevents'], rows: [
        ['001 Clean Architecture', '4-layer dependency rule', 'Structural drift'],
        ['002 Multi-Tenancy RLS', 'Data isolation', 'Security drift'],
        ['003 State Machine', '21 states, 26 actions', 'Workflow drift'],
        ['004 Event-Driven', 'Domain events + outbox', 'Integration drift'],
        ['005 SF424 Forms', 'Federal form generation', 'Compliance drift'],
        ['006 JWT + RBAC', 'Auth + authorization', 'Security drift'],
        ['007 RESTful API', 'Response format', 'Behavioral drift'],
        ['008 RuVector Self-Learning', 'AI/ML integration', 'Architecture drift'],
        ['009 Scaffolding', 'Rapid assembly', 'Process drift'],
        ['010 E2E Testing', 'Playwright patterns', 'Quality drift'],
      ]},
      { type: 'list', items: [
        'Layer 1: CLAUDE.md \u2192 "Use hierarchical topology"',
        'Layer 2: ADRs (10) \u2192 Architectural patterns',
        'Layer 3: DDD (7 contexts) \u2192 Domain boundaries',
        'Layer 4: Swarm (reviewer) \u2192 Quality gate',
      ]},
    ],
    footer: 'ADRs are your guardrails -- write them BEFORE agents code.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 14 — Repository Structure
  // ─────────────────────────────────────────────────
  {
    id: 14,
    title: 'Repository Structure',
    subtitle: 'Clean Architecture: 4 Layers',
    template: 'code',
    transition: 'slideLeft',
    background: 'geometric',
    accentColor: '#2eb85c',
    sections: [
      { type: 'code', language: 'text', content: 'huron-bangalore/\n\u251C\u2500\u2500 src/\n\u2502   \u251C\u2500\u2500 backend/                 # Go Clean Architecture\n\u2502   \u2502   \u251C\u2500\u2500 cmd/server/          # main.go entry point\n\u2502   \u2502   \u2514\u2500\u2500 internal/\n\u2502   \u2502       \u251C\u2500\u2500 domain/          # Pure business logic\n\u2502   \u2502       \u251C\u2500\u2500 application/     # Use cases & services\n\u2502   \u2502       \u251C\u2500\u2500 infrastructure/  # Postgres, RuVector, Embeddings\n\u2502   \u2502       \u2514\u2500\u2500 interfaces/http/ # Handlers + middleware\n\u2502   \u2514\u2500\u2500 frontend/                # Next.js 14\n\u2502       \u251C\u2500\u2500 app/                 # App Router pages\n\u2502       \u251C\u2500\u2500 components/          # React (shadcn/ui)\n\u2502       \u2514\u2500\u2500 lib/wasm/            # rvlite offline search\n\u251C\u2500\u2500 architecture/adrs/           # 10 ADRs\n\u2514\u2500\u2500 CLAUDE.md                    # AI agent instructions' },
      { type: 'diagram', content: 'CLEAN_ARCHITECTURE' },
    ],
    footer: 'Dependencies flow INWARD only. Infrastructure implements domain interfaces.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 15 — Database, Auth & Multi-Tenancy
  // ─────────────────────────────────────────────────
  {
    id: 15,
    title: 'Database, Auth & Multi-Tenancy',
    subtitle: 'PostgreSQL + pgvector + Row-Level Security',
    template: 'code',
    transition: 'slideLeft',
    background: 'circuitBoard',
    accentColor: '#f9a825',
    sections: [
      { type: 'code', language: 'sql', content: "-- Row-Level Security in 4 Lines\nALTER TABLE proposals ENABLE ROW LEVEL SECURITY;\n\nCREATE POLICY tenant_isolation ON proposals\n    USING (tenant_id = current_setting('app.tenant_id')::uuid);\n\nSET LOCAL app.tenant_id = 'tenant-uuid-here';\n\n-- ALL queries now auto-filtered\nSELECT * FROM proposals;\n-- Becomes: WHERE tenant_id = '...'  automatically" },
      { type: 'code', language: 'sql', content: "-- Vector search with HNSW index\nCREATE TABLE proposals (\n    id        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n    tenant_id UUID NOT NULL REFERENCES tenants(id),\n    title     TEXT NOT NULL,\n    status    TEXT NOT NULL DEFAULT 'draft',\n    embedding vector(384),\n    created_at TIMESTAMPTZ DEFAULT NOW()\n);\n\nCREATE INDEX proposals_embedding_idx ON proposals\n    USING hnsw (embedding vector_cosine_ops)\n    WITH (m = 16, ef_construction = 64);" },
    ],
    footer: 'Every query is auto-filtered by tenant. You cannot bypass RLS.',
  },

  // ═══════════════════════════════════════════════════
  // SECTION DIVIDER — Deep Dive: The Stack
  // ═══════════════════════════════════════════════════
  {
    id: 16,
    title: 'Deep Dive: The Stack',
    subtitle: 'RuVector Search, Go Backend, Next.js Frontend, and Self-Learning AI',
    template: 'title',
    transition: 'zoom',
    background: 'neuralNetwork',
    accentColor: '#0bbccc',
    sections: [
      { type: 'text', content: 'Four components working in concert: vector search, domain logic, modern UI, and adaptive intelligence.' },
      { type: 'text', content: 'Each piece was built by specialized AI agents with architectural guardrails.' },
    ],
    footer: 'Every layer designed for autonomy, coordinated for coherence.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 17 — RuVector Deep Dive
  // ─────────────────────────────────────────────────
  {
    id: 17,
    title: 'RuVector Deep Dive',
    subtitle: 'The Self-Learning Search Pipeline',
    template: 'split',
    transition: 'zoom',
    background: 'neuralNetwork',
    accentColor: '#0bbccc',
    sections: [
      { type: 'table', headers: ['Component', 'What It Does', 'Latency'], rows: [
        ['ruvector-postgres', 'Server-side similarity search via pgvector HNSW', '<30ms'],
        ['rvlite (WASM)', 'Browser offline vector search, no server needed', '<80ms'],
        ['ruvector-attention', 'Self-attention re-ranking for relevance', '<10ms'],
        ['ruvector-gnn', 'Graph neural network for entity relationships', '<50ms'],
      ]},
      { type: 'list', items: [
        '1. EMBED \u2192 Text \u2192 384-dim vector (MiniLM-L6-v2)',
        '2. SEARCH \u2192 Cosine similarity, HNSW index',
        '3. RANK \u2192 Attention re-scoring + GNN relationship boost',
        '4. RESULTS \u2192 Top-K proposals with similarity scores',
      ]},
      { type: 'code', language: 'sql', content: "SELECT id, title,\n  1 - (embedding <=> query_vec) AS similarity\nFROM proposals\nWHERE tenant_id = current_setting('app.tenant_id')\nORDER BY embedding <=> query_vec\nLIMIT 10;" },
    ],
    footer: 'Four components, one search pipeline.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 18 — Backend Go
  // ─────────────────────────────────────────────────
  {
    id: 18,
    title: 'Backend: Go Domain + API',
    subtitle: '6-Layer Middleware Stack',
    template: 'code',
    transition: 'slideLeft',
    background: 'geometric',
    accentColor: '#2eb85c',
    sections: [
      { type: 'code', language: 'go', content: '// domain/proposal/entity.go\ntype Proposal struct {\n    ID        uuid.UUID\n    TenantID  uuid.UUID\n    Title     string\n    Status    ProposalStatus\n    PI        PersonRef\n    Budget    BudgetRef\n}\n\nfunc (p *Proposal) Submit() error {\n    if p.Status != StatusDraft {\n        return ErrInvalidTransition\n    }\n    if p.Budget.IsEmpty() {\n        return ErrBudgetRequired\n    }\n    p.Status = StatusSubmitted\n    p.AddEvent(ProposalSubmitted{\n        ProposalID: p.ID,\n        SubmittedAt: time.Now(),\n    })\n    return nil\n}' },
      { type: 'list', items: [
        '1. CORS \u2192 Origin validation',
        '2. Rate Limiter \u2192 100 req/min/tenant',
        '3. Auth (JWT) \u2192 Token validation',
        '4. Tenant (RLS) \u2192 SET LOCAL tenant_id',
        '5. Logger \u2192 Structured logging (zerolog)',
        '6. AIDefence \u2192 Input sanitization',
      ]},
    ],
    footer: 'Pure domain logic -- no HTTP, no SQL, no Redis.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 19 — Frontend
  // ─────────────────────────────────────────────────
  {
    id: 19,
    title: 'Frontend: Next.js Dashboard + WASM',
    subtitle: 'Online + Offline Search',
    template: 'code',
    transition: 'slideLeft',
    background: 'flowingLines',
    accentColor: '#0bbccc',
    sections: [
      { type: 'code', language: 'typescript', content: "// app/dashboard/page.tsx\nexport default async function DashboardPage() {\n  const stats = await fetchDashboardStats();\n  const pipeline = await fetchPipelineData();\n\n  return (\n    <div className=\"grid gap-6 p-6\">\n      <div className=\"grid grid-cols-3 gap-4\">\n        <StatCard title=\"Active Grants\" value={stats.active} />\n        <StatCard title=\"Pending Reviews\" value={stats.pending} />\n        <StatCard title=\"Total Budget\" value={stats.budget} />\n      </div>\n      <Pipeline data={pipeline} />\n      <SearchBar placeholder=\"Search proposals...\" />\n    </div>\n  );\n}" },
      { type: 'code', language: 'typescript', content: "// WASM Offline Fallback\nconst index = await VectorIndex.initialize({\n  dimensions: 384,\n  maxElements: 10000,\n  distanceMetric: 'cosine'\n});\n\nconst results = await index.search(queryEmbedding, {\n  topK: 10, threshold: 0.3\n});\n// Works completely offline in the browser" },
    ],
    footer: "Both paths return the same format. Users don't notice the switch.",
  },

  // ─────────────────────────────────────────────────
  // SLIDE 20 — Self-Learning
  // ─────────────────────────────────────────────────
  {
    id: 20,
    title: 'Self-Learning & Self-Optimizing',
    subtitle: 'SONA Engine + Swarm Optimization',
    template: 'split',
    transition: 'zoom',
    background: 'neuralNetwork',
    accentColor: '#f9a825',
    sections: [
      { type: 'list', items: [
        'Mixture of Experts (MoE) -- Route queries to specialized models',
        'HNSW Indexing -- Self-organizing O(log n) search',
        'EWC++ -- Prevents catastrophic forgetting',
        'LoRA Fine-Tuning -- Low-rank adaptation per tenant',
      ]},
      { type: 'diagram', content: 'SELF_LEARNING_LOOP' },
      { type: 'code', language: 'bash', content: '# Store learned patterns\nnpx @claude-flow/cli memory store \\\n  --namespace ruvector \\\n  --key "cancer-search-opt" \\\n  --value "Boost MeSH term embeddings 1.3x for NIH queries"\n\n# Next agent retrieves automatically\nnpx @claude-flow/cli memory search \\\n  --query "optimize cancer grant search" \\\n  --namespace ruvector' },
    ],
    footer: 'The system gets smarter without retraining.',
  },

  // ═══════════════════════════════════════════════════
  // SECTION DIVIDER — Let's Build
  // ═══════════════════════════════════════════════════
  {
    id: 21,
    title: 'Let\'s Build',
    subtitle: 'From Zero to Working Prototype -- Live, With Agent Swarms',
    template: 'title',
    transition: 'zoom',
    background: 'particles',
    accentColor: '#f9a825',
    sections: [
      { type: 'text', content: '5 phases. 6 agents. Under 2 hours.' },
      { type: 'text', content: 'Watch coordinated AI agents build a production-grade system in real time.' },
    ],
    footer: 'Hands on keyboards. Agents on task. Let\'s ship.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 22 — Live Build
  // ─────────────────────────────────────────────────
  {
    id: 22,
    title: 'Live Build: Prototype in Under 2 Hours',
    subtitle: 'The 5-Phase Plan',
    template: 'content',
    transition: 'slideLeft',
    background: 'particles',
    accentColor: '#f9a825',
    sections: [
      { type: 'list', items: [
        'Phase 1: SETUP (15 min) -- ./start-hacking.sh, environment, Docker',
        'Phase 2: BACKEND (30 min) -- Domain, REST API, RuVector, RLS',
        'Phase 3: FRONTEND (30 min) -- Dashboard, search, WASM fallback',
        'Phase 4: INTEGRATION (30 min) -- E2E testing, demo data',
        'Phase 5: DEMO PREP (15 min) -- Run-through, performance checks',
      ]},
      { type: 'code', language: 'bash', content: '# Phase 2: Backend Swarm\nclaude "Initialize a hierarchical swarm with 4 agents:\n  - Researcher: Read ADR-001, ADR-002, ADR-003\n  - Backend-dev: Implement proposal handlers\n  - Backend-dev: Implement postgres repositories\n  - Tester: Write integration tests\n  Follow Clean Architecture. Use RLS."' },
      { type: 'code', language: 'bash', content: '# Phase 3: Frontend Swarm\nclaude "Initialize a hierarchical swarm with 4 agents:\n  - Researcher: Read existing components\n  - Coder: Build dashboard\n  - Coder: Build proposal search with WASM\n  - Tester: Write Playwright E2E tests"' },
    ],
    footer: 'Swarm > Solo: 6 agents always beats 1 agent.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 23 — Testing
  // ─────────────────────────────────────────────────
  {
    id: 23,
    title: 'Testing, Validation & Demo',
    subtitle: 'Playwright + Validation Checklist',
    template: 'code',
    transition: 'fade',
    background: 'geometric',
    accentColor: '#2eb85c',
    sections: [
      { type: 'code', language: 'typescript', content: "test('create and submit a proposal', async ({ page }) => {\n  await page.goto('/proposals/new');\n  await page.fill('[name=\"title\"]', 'NIH R01 Grant');\n  await page.click('button[type=\"submit\"]');\n  await expect(page.locator('.status-badge')).toHaveText('Draft');\n\n  await page.click('button:has-text(\"Submit\")');\n  await expect(page.locator('.status-badge')).toHaveText('Submitted');\n});\n\ntest('semantic search finds relevant proposals', async ({ page }) => {\n  await page.goto('/search');\n  await page.fill('[name=\"search\"]', 'cancer research NIH');\n  const results = page.locator('.search-result');\n  await expect(results).toHaveCount({ minimum: 1 });\n});" },
      { type: 'list', items: [
        'Architecture: Clean Architecture layers respected, domain has no external deps',
        'Security: RLS enabled on all tenant tables, JWT on all endpoints',
        'Functionality: CRUD works, vector search returns results, WASM fallback works',
        'Performance: Vector search <50ms, WASM <100ms, API <200ms',
      ]},
    ],
    footer: 'Test everything -- E2E tests validate the full stack.',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 24 — Key Takeaways
  // ─────────────────────────────────────────────────
  {
    id: 24,
    title: 'Key Takeaways',
    subtitle: '8 Principles for Agentic Engineering',
    template: 'content',
    transition: 'fade',
    background: 'flowingLines',
    accentColor: '#0bbccc',
    sections: [
      { type: 'list', items: [
        'ADRs are your guardrails -- write them BEFORE agents code',
        'DDD gives agents context -- bounded contexts prevent drift',
        'Hierarchical topology -- best for hackathons and small teams',
        'CLAUDE.md is your control file -- the AI reads this first',
        'Memory compounds -- stored patterns improve every iteration',
        'Swarm > Solo -- 6 agents always beats 1 agent',
        'Test everything -- E2E tests validate the full stack',
        'Self-learning is real -- RuVector SONA gets better over time',
      ]},
      { type: 'quote', content: 'The future of software engineering is agentic. You now have the tools. Go build something extraordinary. -- rUv' },
    ],
    footer: 'Architecture + Agents + Memory = Production-Grade AI-Native Apps',
  },

  // ─────────────────────────────────────────────────
  // SLIDE 25 — Thank You & Resources
  // ─────────────────────────────────────────────────
  {
    id: 25,
    title: 'Thank You',
    subtitle: 'Go Build Something Extraordinary',
    template: 'title',
    transition: 'fade',
    background: 'particles',
    accentColor: '#0bbccc',
    sections: [
      { type: 'text', content: 'rUv (Reuven Cohen) -- ruv.net' },
      { type: 'text', content: 'github.com/ruvnet/huron-bangalore' },
      { type: 'text', content: 'github.com/ruvnet/claude-flow' },
    ],
    footer: 'Bangalore Hackathon | Presented by rUv',
  },
];
