#!/usr/bin/env bash
# =============================================================================
# generate-presentation.sh
# Generates the complete Bangalore Hackathon presentation from slide files
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRES_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="${PRES_DIR}/FULL-PRESENTATION.md"
SLIDES_DIR="${PRES_DIR}/slides"
ADRS_DIR="${PRES_DIR}/adrs"

echo "================================================================="
echo "  Bangalore Hackathon Presentation Generator"
echo "  Agentic Engineering: Building AI-Native Apps in Under 2 Hours"
echo "================================================================="
echo ""

# Header
cat > "$OUTPUT_FILE" << 'HEADER'
# Agentic Engineering: Building AI-Native Apps in Under 2 Hours
## Bangalore Hackathon Presentation

**Presented by**: rUv (Reuven Cohen)
**Duration**: ~75 minutes (20 slides)
**Format**: Workshop + Live Build

---

> **How to use this document**: Each section is a slide. Present top-to-bottom.
> Code blocks are meant to be shown/demonstrated live.
> ASCII diagrams replace visual slides.
> [ILLUSTRATION] tags describe images to create separately.

---

HEADER

echo "Generating presentation..."

# Concatenate all slides
for i in $(seq -w 1 20); do
  SLIDE_FILE="${SLIDES_DIR}/slide-${i}.md"
  if [ -f "$SLIDE_FILE" ]; then
    echo "  Adding slide ${i}..."
    echo "" >> "$OUTPUT_FILE"
    echo "---" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    cat "$SLIDE_FILE" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
  else
    echo "  WARNING: Missing slide-${i}.md"
  fi
done

# Add appendix with ADR summaries
cat >> "$OUTPUT_FILE" << 'APPENDIX'

---

# Appendix: Presentation ADR Index

| ADR | Slide | Key Message |
|-----|-------|-------------|
| PRES-001 | Welcome | Agentic Engineering is intent-driven development |
| PRES-002 | Toolchain | Claude Code writes, Claude Flow orchestrates, RuVector searches |
| PRES-003 | Claude Code | CLAUDE.md is your AI instruction manual |
| PRES-004 | Claude Flow + RuVector | npx for Flow, Docker for RuVector |
| PRES-005 | RuVector Deep Dive | 4 components, one pipeline |
| PRES-006 | ADRs | Executable instructions for AI agents |
| PRES-007 | DDD | Shared language and clear boundaries |
| PRES-008 | Anti-Drift | Without guardrails, iteration 20 is chaos |
| PRES-009 | Repo Structure | Dependencies flow inward only |
| PRES-010 | Setup | Codespaces for zero friction |
| PRES-011 | Go Backend | Domain layer has zero external dependencies |
| PRES-012 | Next.js Frontend | Server components + WASM offline |
| PRES-013 | Database + Auth | RLS auto-filters every query by tenant |
| PRES-014 | Dashboard | Swarm builds UI in parallel |
| PRES-015 | Middleware | 6 layers process every request |
| PRES-016 | Self-Learning | System improves with every interaction |
| PRES-017 | Self-Optimizing | 6 agents > 1 agent, always |
| PRES-018 | Live Build | Zero to prototype in 5 phases |
| PRES-019 | Testing | Testing is built-in, not bolted-on |
| PRES-020 | Wrap-Up | Go build something extraordinary |

---

*Generated by generate-presentation.sh*
*Co-Authored-By: claude-flow <ruv@ruv.net>*
APPENDIX

echo ""
echo "Presentation generated: ${OUTPUT_FILE}"
echo "Slides: 20"
echo "ADRs: 20"
echo ""
echo "To present: Open ${OUTPUT_FILE} in any Markdown viewer"
echo "For slides: Use Marp, Slidev, or reveal.js with the individual files"
